---
about: true
animation: true
authors:
  jacoblaboissonniere:
    bio: "Third year Software Engineering (Co-op) at Carleton University"
    external-image: false
    name: "Jacob Laboissonniere"
    picture: assets/images/profile.jpg
    twitter: jacoblab1
bio: "Third year Software Engineering (Co-op) at Carleton University"
blog: true
description: "A blog about technology and stuff related"
disqus:
  categories:
    - blog
    - project
  shortname: mydisqus
email: jacob.laboissonniere@carleton.ca
external-image: false
github: jacoblab1
instagram: jacoblab1
jekyll-mentions:
  base_url: "https://github.com"
linkedin: jacoblaboissonniere
name: "Jacob Laboissonniere"
permalink: "/:title/"
picture: assets/images/profile.jpg
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
post-advance-links:
  - blog
projects: false
read-time: true
related: true
resume: false
resume-external: true
resume-url: "https://google.com/?q=my+resume"
show-author: true
show-tags: true
url: "https://jacoblab.me"
width: normal
